### ISSUE TITLE
[Bug] Error is always printed despite `patched_api_key` is not set.

### ISSUE THREAD

**Issue by CTY-git** [patched-codes/patchwork#150]
When `patched_api_key` is not set, a error should not be printed to the console. The error should only be printed to the console if `patched_api_key` is set and is found to be invalid after testing the token through a REST API call.

**Comment by patched-admin** [comment]
The following files in the repository may be relevant to the issue:

------

* patchwork/common/client/patched.py
* patchwork/steps/CreateIssueComment/CreateIssueComment.py
* patchwork/steps/ReadIssues/ReadIssues.py
* patchwork/steps/CreatePRComment/CreatePRComment.py
* patchwork/app.py
* patchwork/steps/CallLLM/CallLLM.py
* patchwork/steps/ModifyCode/ModifyCode.py
* patchwork/steps/PreparePrompt/PreparePrompt.py

**Comment by codelion** [comment]
Fixed in #146
