### ISSUE TITLE
progress bar on long running steps

### ISSUE THREAD

**Issue by patched-admin** [patched-codes/patchwork#3]
E.g. in CallOpenAI step we can wrap this loop (https://github.com/patched-codes/patchwork/blob/master/patchwork/steps/CallOpenAI/CallOpenAI.py#L47) with tqdm to get a nice progress bar.

**Comment by patched-admin** [comment]
The following files in the repository may be relevant to the issue:

------

* patchwork/steps/CallLLM/CallLLM.py
* patchwork/steps/ExtractCode/ExtractCode.py
* patchwork/common/client/patched.py
* patchwork/patchflows/DependencyUpgrade/DependencyUpgrade.py
* patchwork/steps/QueryEmbeddings/QueryEmbeddings.py

**Comment by codelion** [comment]
fixed in #211
