### ISSUE TITLE
Improve handling of disable_pr option

### ISSUE THREAD

**Issue by codelion** [patched-codes/patchwork#356]
Handle the following condition more gracefully, when the pr creation is disabled the user shouldn't expected to be add the github_api_key. 

- When the user chooses `--disable_pr` we still require the presence of the `github_api_key` or the `gitlab_api_key`. As a result the patchflow errors out.

**Comment by staru09** [comment]
Is this open to work?

**Comment by codelion** [comment]
@staru09 yes this is available to work you can submit a PR.

**Comment by staru09** [comment]
ok cool

**Comment by staru09** [comment]
I have submitted the PR. 
Kindly review.

**Comment by codelion** [comment]
fixed in #448
