### ISSUE TITLE
Link to file changed not correct

### ISSUE THREAD

**Issue by codelion** [patched-codes/patchwork#39]
In the PR the links to file and the changes are not correct. E.g. https://github.com/codelion/dvpwa/pull/16

The link on /Users/user/Documents/GitHub/dvpwa/docker-compose.yml is pointing to https://github.com/codelion/dvpwa/pull/16/files#diff-73d2c5aa8a84b134c0d026689a5fd1fcf3b6696d87236126c2f1d6c5c0a53573 
instead of 
https://github.com/codelion/dvpwa/pull/16/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3

**Comment by codelion** [comment]
When we enable suggestion with the PRReview flow I think the partitioning has some issue see - https://github.com/codelion/example-python/pull/37#issuecomment-2068508947

**Comment by CTY-git** [comment]
I have found the following files in the code repository that may be relevant to the issue:
------

* patchwork/steps/ReadPRDiffs/ReadPRDiffs.py
* patchwork/common/client/scm.py
* patchwork/steps/ExtractDiff/ExtractDiff.py
