### ISSUE TITLE
Improvement Proposal: Revamp Readme.md File

### ISSUE THREAD

**Issue by Greyisheep** [patched-codes/patchwork#442]
The current `readme.md` file could benefit from improvements in readability, structure, and clarity. I propose the following changes:
- Reformatting sections for better readability.
- Clarifying installation instructions with detailed examples.
- Ensuring consistency in key terms.
- Enhancing the contribution guide and roadmap sections.

## Benefits
- Improved usability for new users and contributors.
- Clearer instructions and better understanding of the project’s features and components.
- More organized and professional documentation.

## Additional Notes
I will create a pull request with the proposed changes and link this issue to it, and discuss documentation in its entirety with the team.

**Comment by codelion** [comment]
fixed in #446
