### ISSUE TITLE
Naming Conflict with patchwork Binary Link Pointing to dot in Graphviz Package on Linux

### ISSUE THREAD

**Issue by hallelujah-shih** [patched-codes/patchwork#500]
A naming conflict issue has been identified with the patchwork binary in the Graphviz package under Linux operating systems. Details are as follows:
OS: Fedora Linux 40 (Workstation Edition)
pkginfo: graphviz-9.0.0-11.fc40.x86_64

**Comment by patched-admin** [comment]
Thanks for flagging this. Is the naming conflict with 'patchwork' or 'patchwork-cli'?

**Comment by patched-admin** [comment]
Closing this for now. Please reopen if needed @hallelujah-shih.
