### ISSUE TITLE
Get Issue title as well for ResolveIssue Patchflow

### ISSUE THREAD

**Issue by codelion** [patched-codes/patchwork#58]
At the moment we only retrieve the body and comments from an Issue as shown here - https://github.com/patched-codes/patchwork/blob/main/patchwork/common/client/scm.py#L303

If the body is empty and there are no comments it will lead to error while querying the embeddings. Retrieve the title as well from the Issue to avoid this.

**Comment by staru09** [comment]
Is this open to work?

**Comment by codelion** [comment]
Yes, this is open to work. Please make sure there are end-to-end test cases or examples others can review when you submit your PR. It can be a link to an example repo like [this](https://github.com/codelion/example-python/issues/40) doesn't have to a test case.

**Comment by prathamjagga** [comment]
@codelion Seems like, we are already getting issue_title in the dictionary returned get_issue_by_id in scm.py which in turn is used by ReadIssues class for reading the issue. I think we can close this issue.

**Comment by codelion** [comment]
@prathamjagga see the comment by @CTY-git [here](https://github.com/patched-codes/patchwork/pull/507#pullrequestreview-2235977194) I think it is best if it is at the step level and not in scm.py

**Comment by codelion** [comment]
I just tested it with https://github.com/codelion/example-python/issues/56 I think it is working fine.
