### ISSUE TITLE
Value of open ai for local models such as ollama

### ISSUE THREAD

**Issue by abhishek9sharma** [patched-codes/patchwork#676]
It seems that for running against local models such as ollama the value of `openai_api_key` needs to be `no_key_open_source_local`. 

Reference : https://github.com/patched-codes/patchwork-configs/blob/main/patchflows/GenerateDocstring/config.yml#L7

Should above be mentioned in README.md

**Comment by codelion** [comment]
Usually for running locally some value needs to be present, depending on what you are using. E.g. in Ollama it should be 'ollama' as mentioned in their docs - https://ollama.com/blog/openai-compatibility If you use llama.cpp directly you can put any value.

**Comment by abhishek9sharma** [comment]
Thanks makes sense. Seems it works with both values `no_key_open_source_local` as well as `ollama'.

Closing this
