### ISSUE TITLE
Create a new patchflow that can generate unit tests

### ISSUE THREAD

**Issue by codelion** [patched-codes/patchwork#864]
- Allow users to specify classes to test
- Automatically generate unit tests for methods in those classes
- Decide on what framework we will use for generating tests

**Comment by plon-Susk7** [comment]
Hey @codelion , I'd love to work on this issue.

**Comment by codelion** [comment]
Please go ahead, look forward to your PR.

**Comment by plon-Susk7** [comment]
@codelion , is it fine if I use together's api for this issue?

**Comment by plon-Susk7** [comment]
I was able to setup the project but I got this error while running pathflows

![image](https://github.com/user-attachments/assets/ec02724a-79c9-4c64-bda1-ea520091ddd1)

**Comment by plon-Susk7** [comment]
Hey @codelion ,
I was having some trouble running few of your steps. Here's the error

![image](https://github.com/user-attachments/assets/6d83bf8a-f2e2-432a-9f44-811371910fb2)

When i run poetry show semgrep it shows the package but for some reason its failing here.

**Comment by plon-Susk7** [comment]
Hey @codelion , I've been working on this issue. I had few doubts. Is it possible to discuss the doubts on call whenever you're free?

**Comment by codelion** [comment]
@plon-Susk7 sure, you can dm me on discord to discuss.

**Comment by codelion** [comment]
Fixed in #998
