### ISSUE TITLE
My repo don't show up

### ISSUE THREAD

**Issue by femto** [patched-codes/patchwork#926]
I'm trying patchflow,
but adding repositories don't show up my several repos:
https://github.com/femto/minion
https://github.com/femto/MetaGPT
https://github.com/MadcowD/ell
etc, only other repos

**Comment by femto** [comment]
<img width="1853" alt="image" src="https://github.com/user-attachments/assets/2d6c42a4-019f-4b3f-8a33-966e987bb835">
I haven't tried any workflow yet, I can't add my minion framework

**Comment by codelion** [comment]
This is in the app, what is your org id? You can find it in the URL at the page you are at `https://app.patched.codes/65/repositories` it is the number in between e.g. 65.

Usually issues with adding the repo are related to permissions. Are you able to add any open-source repo or any other repo in your account? You need to install the GH app in the org and give permission to access repos to be able to add it.

**Comment by femto** [comment]
https://app.patched.codes/721/repositories/manage 

I give github permission to your app.
currently it has 4 pages of repositories,
but unfortunately the three I mentioned all don't show up,
which is very weird.

**Comment by codelion** [comment]
@femto at the moment we only import the first 100 repos from a GitHub org, it looks like you may have more than that. We will add this ticket to the backlog to address it soon. Thanks for reporting. Meanwhile, feel free to grab some time on my [calendar](https://calendly.com/asankhaya-patchedcodes/intro-demo?month=2024-10&date=2024-10-01) to help us understand your use case better.

**Comment by femto** [comment]
Could you manually add my 3 repos mentioned here? Recently I'm committing to these repos.
I don't have a use case in mind, I came from optillm, just want to check out what patchflow can do.
May ai doing code review for me or ai writing documentation for me?
'use case' means my patchflow use case or my minion 'use case' ?
Let me reading the papers you mentioned in optillm first, after that,
I'll grab some time to chat with you.

**Comment by codelion** [comment]
@femto This is not fixed, can you please try again and see if you can use it with your repos.

**Comment by femto** [comment]
@codelion hello, I see these repos been manually added, should I delete them to try to add back?

 I tried several flows:
Autofix seems promising, but why does it change my logic?
https://github.com/femto/minion/pull/1/files#diff-bd4c40aa4984117765885d4ecbaec5a2d5ec7387f881da08510e17ce5b62deb7,

GenerateReadme is also weird,nearly completely remove my original stuff,
https://github.com/femto/minion/pull/4,

Also, it seemed Fair use limit exceeded, I can't test more.

**Comment by codelion** [comment]
Yes, you can try deleting and checking if they show up in the list to try again.

Autofix seems to suggest that the use of `eval` is unsafe and that's why it suggests filtering the expressions in a different method. For what you are doing it seems totally fine so you can actually adjust the `compatibility` to avoid making changes.

The default GenerateREADME workflow creates a new doc but doesn't update the existing document. We can edit that in the patchflow builder as needed. 

Happt to chat with you more and add some credits so that you can try it out, please feel free to grab some time on my calendar here - https://calendly.com/asankhaya-patchedcodes/intro-demo

**Comment by femto** [comment]
I deleted and readded thru Manage button, it's fine.
<img width="1886" alt="image" src="https://github.com/user-attachments/assets/898c6de1-bf7e-4e3b-b20b-99298553c244">
but it seemed more natural to just add edit setting/delete right besides this img?

**Comment by codelion** [comment]
Sure, we will review the ux to make it better. Thanks.
