### ISSUE TITLE
Javadocs is created with ``` 

### ISSUE THREAD

**Issue by gkorland** [patched-codes/patchwork#935]
Javadocs comments are created with surrounding ``` which are breaking to java compilation.

See example: https://github.com/FalkorDB/JFalkorDB/pull/71

**Comment by prathamjagga** [comment]
@gkorland can you explain a bit about it, what exactly is happening. In the commits of the Pull Request you mentioned, I see the docstrings are correct.

**Comment by gkorland** [comment]
The PR can't be merged, using ``` is not a legal Javadoc

**Comment by codelion** [comment]
@gkorland This should be fixed now, please let me know if you still run into the issue. (Here is an example Java project that we tested with https://github.com/patched-codes/AltoroJ/pull/23)
