### ISSUE TITLE
Branches list on patch view is limited

### ISSUE THREAD

**Issue by gkorland** [patched-codes/patchwork#936]
It seems like the branches drop down list on the patch popup view is limited by size so the right branch can't be chosen. 

![image](https://github.com/user-attachments/assets/541945d7-b370-4012-86cd-b9803a07adbf)

**Comment by codelion** [comment]
I think there is a limit on the number of branches we pull in. We will get this fixed.

**Comment by codelion** [comment]
@gkorland This is fixed now, try it out again see if you are able to see your branches.
