### ISSUE TITLE
Unable to create a PR when run Autofix patchflow

### ISSUE THREAD

**Issue by premjaisinghanii** [patched-codes/patchwork#941]
- I have cloned the repo and running this workflow locally

`patchwork AutoFix client_base_url=http://localhost:8000/v1 openai_api_key=no_key_local_model github_api_key=git_hub_api key`

When i run this command in local machine:
Here are the logs:

 Run started PreparePR                                                                          
 Run completed PreparePR                                                                        
 Run started CreatePR                                                                           
 Creating PR from dev-111 to autofix-dev-111 
Step CreatePR failed                                                                       
Step PR failed                                                                                 
Error running patchflow AutoFix: 404 {"message": "Not Found", "documentation_url":           
"https://docs.github.com/rest/repos/repos#get-a-repository", "status": "404"}

Can anyone help with this? not sure how to resolve, any git repo permission issue?

**Comment by codelion** [comment]
@premjaisinghanii Do you have the right github token that has permissions on the repository? Do you see the changes in your local autofix-dev-111 branch after running the patchflow?

**Comment by premjaisinghani** [comment]
> @premjaisinghanii Do you have the right github token that has permissions on the repository? Do you see the changes in your local autofix-dev-111 branch after running the patchflow?

Yes we can see the changes in the local branch and We have given the permission also in github token. Is any specific permission require ?

**Comment by premjaisinghanii** [comment]
> @premjaisinghanii Do you have the right github token that has permissions on the repository? Do you see the changes in your local autofix-dev-111 branch after running the patchflow?

Yes we can see the changes in the local branch and We have given the permission also in github token. Is any specific permission require ?

**Comment by codelion** [comment]
We need a token that has the following permissions:
 
<img width="399" alt="Screenshot 2024-10-10 at 4 11 43 PM" src="https://github.com/user-attachments/assets/8555ba31-b3d9-4dc6-a57a-c35888728f23">

**Comment by premjaisinghanii** [comment]
We have already given the permission
<img width="430" alt="Screenshot 2024-10-10 at 3 42 35 PM" src="https://github.com/user-attachments/assets/38733d3e-ac65-4df1-82be-7a9306ea227f">

**Comment by codelion** [comment]
Can you run with `--debug` and go through each step and share the output log that is printed on the CLI.

**Comment by premjaisinghanii** [comment]
> Can you run with `--debug` and go through each step and share the output log that is printed on the CLI. Make sure you scrub the keys that are printed in the logs.

Patchflow AutoFix logs
Run started ScanSemgrep                                                                                                                                             
Run completed ScanSemgrep                                                                                                                                          
Run started ExtractCode                                                                                                                                             
Found 2 results from SARIF data                                                                                                                                     
Run completed ExtractCode                                                                                                                                           
Run started LLM                                                                                                                                                     
Run started PreparePrompt                                                                                                                                           
Run completed PreparePrompt                                                                                                                                        
Run started CallLLM                                                                                                                                                 
Run completed CallLLM                                                                                                                                               
Run started ExtractModelResponse                                                                                                                                   
Run completed ExtractModelResponse                                                                                                                                  
Run completed LLM                                                                                                                                                   
Run started ModifyCode                                                                                                                                              
Run completed ModifyCode                                                                                                                                            
Run started PR                                                                                                                                                      
Run started CommitChanges                                                                                                                                           
Creating new branch "autofix-dev-111".                                                                                                                              
Run completed CommitChanges                                                                                                                                         
Run started PreparePR                                                                                                                                               
Run completed PreparePR                                                                                                                                             
Run started CreatePR                                                                                                                                                
Creating PR from dev-111 to autofix-dev-111                                                                                                                        
Step CreatePR failed                                                                                                                                                
Step PR failed                                                                                                                                                      
Error running patchflow AutoFix: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/repos/repos#get-a-repository", "status": "404"}

**Comment by codelion** [comment]
I think you are not on the latest version can you see if 

`patchwork --version`

gives 

```
(patchwork-cli-py3.12) codelion@Asankhayas-MBP example-python % patchwork --version
0.0.68
```

**Comment by premjaisinghanii** [comment]
`Run started PreparePR                                                                                                                                                  
Run completed PreparePR                                                                                                                                                
                                                                                                                                                                       
Inputs:                                                                                                                                                                
base_branch: dev-111                                                                                                                                                   
target_branch: autofix-dev-111                                                                                                                                         
pr_body: This pull request from patched fixes 1 issues.                                                                                                                
                                                                                                                                                                       
------                                                                                                                                                                 
                                                                                                                                                                       
<div markdown="1">                                                                                                                                                     
                                                                                                                                                                       
* File changed: [pr.py]({{pr.py}})<details><summary>Parameterize query to prevent SQL Injection</summary>  Replaced string formatting with parameterized queries   
using SQLite's ? placeholder for SQL injection prevention.</details>                                                                                                   
                                                                                                                                                                       
</div>                                                                                                                                                                 
compatibility: unknown                                                                                                                                                 
vulnerability_limit: 10                                                                                                                                                
context_size: 1000                                                                                                                                                     
severity: unknown                                                                                                                                                      
disable_branch: False                                                                                                                                                  
disable_pr: False                                                                                                                                                      
force_pr_creation: True                                                                                                                                                
debug: True                                                                                                                                                            
client_base_url: http://localhost:8000/v1                                                                                                                              
openai_api_key:                                                                                                                                                        
sk-proj- {open_api_key} 
github_api_key: {git_hub_key}
prompt_id: fixprompt                                                                                                                                                   
pr_title: PatchWork AutoFix                                                                                                                                            
branch_prefix: autofix-                                                                                                                                                
request_tokens: [611]                                                                                                                                                  
response_tokens: [136]                                                                                                                                                 
                                                                                                                                                                       
                                                                                                                                                                       
Press enter to continue, any other key to exit...                                                                                                                      
                                                                                                                                                                       
Continuing...                                                                                                                                                          
                                                                                                                                                                       
Run started CreatePR                                                                                                                                                   
Creating PR from dev-111 to autofix-dev-111                                                                                                                            
Step CreatePR failed                                                                                                                                                   
Step PR failed                                                                                                                                                         
Error running patchflow AutoFix: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest", "status": "401"} `


Earlier it was giving :
Error running patchflow AutoFix: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/repos/repos#get-a-repository", "status": "404"} error message

**Comment by codelion** [comment]
This points to an error with the token itself. Can you see what reponse you get when youc all the GitHub API directly with your token:

```
curl -L \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/OWNER/REPO/pulls \
  -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"octocat:new-feature","base":"master"}'
  ```
  
Btw, if your repo is under a org, you will need an org token even if your personal account has access to the repo it will not work with your personal token.

**Comment by premjaisinghanii** [comment]
Thank you very much! The issue has been resolved.
